// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3P8prB1FW0BDoulme2OO3HNesMSLHi3c',
    appId: '1:260824564206:web:329df5fc1c58151306ceff',
    messagingSenderId: '260824564206',
    projectId: 'reddit-clone-d8c0c',
    authDomain: 'reddit-clone-d8c0c.firebaseapp.com',
    storageBucket: 'reddit-clone-d8c0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUHD2Zz6HCXcxvy10ID71BfPOQWR9Ol0w',
    appId: '1:260824564206:android:ef00d99ba1bb7a6a06ceff',
    messagingSenderId: '260824564206',
    projectId: 'reddit-clone-d8c0c',
    storageBucket: 'reddit-clone-d8c0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHE_GPW8DTr0VwkNDb78l_IKep17ug1RI',
    appId: '1:260824564206:ios:0e7128ed224a961106ceff',
    messagingSenderId: '260824564206',
    projectId: 'reddit-clone-d8c0c',
    storageBucket: 'reddit-clone-d8c0c.firebasestorage.app',
    iosBundleId: 'com.example.reditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHE_GPW8DTr0VwkNDb78l_IKep17ug1RI',
    appId: '1:260824564206:ios:0e7128ed224a961106ceff',
    messagingSenderId: '260824564206',
    projectId: 'reddit-clone-d8c0c',
    storageBucket: 'reddit-clone-d8c0c.firebasestorage.app',
    iosBundleId: 'com.example.reditClone',
  );
}
